-- swagat supermarket database schema

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE categories (
  category_id   SERIAL      PRIMARY KEY,
  category_name VARCHAR(50) NOT NULL
);

CREATE TABLE suppliers (
  supplier_id   SERIAL       PRIMARY KEY,
  supplier_name VARCHAR(100) NOT NULL,
  contact       VARCHAR(100)
);

CREATE TABLE items (
  item_id       SERIAL        PRIMARY KEY,
  category_id   INT           REFERENCES categories(category_id),
  sku           VARCHAR(50)   NOT NULL UNIQUE,
  barcode       VARCHAR(20),
  item_name     VARCHAR(150)  NOT NULL,
  description   TEXT,
  brand         VARCHAR(100),
  retail_price  DECIMAL(10,2) NOT NULL,
  cost_price    DECIMAL(10,2),
  unit          VARCHAR(20),
  reorder_point INT           DEFAULT 0,
  is_perishable BOOLEAN       DEFAULT FALSE,
  is_active     BOOLEAN       DEFAULT TRUE,
  image_url     TEXT,
  created_at    TIMESTAMPTZ   DEFAULT NOW(),
  updated_at    TIMESTAMPTZ   DEFAULT NOW()
);

CREATE TABLE stock_orders (
  order_id     SERIAL       PRIMARY KEY,
  supplier_id  INT          REFERENCES suppliers(supplier_id),
  order_date   DATE         NOT NULL,
  arrival_date DATE,
  notes        VARCHAR(255)
);

CREATE TABLE order_items (
  order_item_id SERIAL        PRIMARY KEY,
  order_id      INT           REFERENCES stock_orders(order_id),
  item_id       INT           REFERENCES items(item_id),
  quantity      INT           NOT NULL,
  unit_cost     DECIMAL(10,2) NOT NULL
);

-- stock changes tracked as movements, not overwritten
-- movement_type: initial_count, delivery, sale, adjustment, return
CREATE TABLE stock_movements (
  movement_id     SERIAL      PRIMARY KEY,
  item_id         INT         REFERENCES items(item_id),
  change_qty      INT         NOT NULL,
  movement_type   VARCHAR(20) NOT NULL,
  occurred_at     TIMESTAMPTZ DEFAULT NOW(),
  source_order_id INT         REFERENCES stock_orders(order_id)
);

-- embeddings generated by sentence-transformers/all-MiniLM-L6-v2
CREATE TABLE item_embeddings (
  item_id   INT         PRIMARY KEY REFERENCES items(item_id) ON DELETE CASCADE,
  embedding vector(384)
);

-- run this after inserting embeddings, not before
CREATE INDEX ON item_embeddings USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);
