-- swagat supermarket database schema

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE categories (
  category_id   SERIAL      PRIMARY KEY,
  category_name VARCHAR(50) NOT NULL
);

CREATE TABLE suppliers (
  supplier_id   SERIAL       PRIMARY KEY,
  supplier_name VARCHAR(100) NOT NULL,
  contact       VARCHAR(100)
);

CREATE TABLE items (
  item_id       SERIAL        PRIMARY KEY,
  category_id   INT           REFERENCES categories(category_id),
  sku           VARCHAR(50)   NOT NULL UNIQUE,
  barcode       VARCHAR(20),
  item_name     VARCHAR(150)  NOT NULL,
  description   TEXT,
  brand         VARCHAR(100),
  retail_price  DECIMAL(10,2) NOT NULL,
  cost_price    DECIMAL(10,2),
  unit          VARCHAR(20),
  reorder_point INT           DEFAULT 0,
  is_perishable BOOLEAN       DEFAULT FALSE,
  is_active     BOOLEAN       DEFAULT TRUE,
  image_url     TEXT,
  created_at    TIMESTAMPTZ   DEFAULT NOW(),
  updated_at    TIMESTAMPTZ   DEFAULT NOW()
);

CREATE TABLE stock_orders (
  order_id     SERIAL       PRIMARY KEY,
  supplier_id  INT          REFERENCES suppliers(supplier_id),
  order_date   DATE         NOT NULL,
  arrival_date DATE,
  notes        VARCHAR(255)
);

CREATE TABLE order_items (
  order_item_id SERIAL        PRIMARY KEY,
  order_id      INT           REFERENCES stock_orders(order_id),
  item_id       INT           REFERENCES items(item_id),
  quantity      INT           NOT NULL,
  unit_cost     DECIMAL(10,2) NOT NULL
);

-- stock changes tracked as movements, not overwritten
-- movement_type: initial_count, delivery, sale, adjustment, return
CREATE TABLE stock_movements (
  movement_id     SERIAL      PRIMARY KEY,
  item_id         INT         REFERENCES items(item_id),
  change_qty      INT         NOT NULL,
  movement_type   VARCHAR(20) NOT NULL,
  occurred_at     TIMESTAMPTZ DEFAULT NOW(),
  source_order_id INT         REFERENCES stock_orders(order_id)
);

-- embeddings generated by sentence-transformers/all-MiniLM-L6-v2
CREATE TABLE item_embeddings (
  item_id   INT         PRIMARY KEY REFERENCES items(item_id) ON DELETE CASCADE,
  embedding vector(384)
);

-- ---------------------------------------------------------------------------
-- Vector index for fast similarity search.
-- Build this AFTER inserting embeddings, not before.
-- NOTE: the original design used ivfflat (Option A). During deployment an HNSW
-- index (Option B) was created in the Supabase console. Confirm which one is
-- actually live in the Supabase dashboard and keep only that one.
-- ---------------------------------------------------------------------------

-- Option A (original design): ivfflat
-- CREATE INDEX ON item_embeddings USING ivfflat (embedding vector_cosine_ops)
--   WITH (lists = 100);

-- Option B (created during deployment): HNSW
CREATE INDEX IF NOT EXISTS item_embeddings_embedding_idx
  ON item_embeddings USING hnsw (embedding vector_cosine_ops);

-- ---------------------------------------------------------------------------
-- Similarity-search function used by the chatbot backend (Backend/chatbot.py).
-- Returns the top-K closest ACTIVE products for a query embedding.
-- Called from Python via: supabase.rpc("match_items", {...}).
-- The <=> operator is pgvector cosine distance; similarity = 1 - distance.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION match_items(
  query_embedding vector(384),
  match_count     int DEFAULT 5
)
RETURNS TABLE (
  item_id      int,
  item_name    varchar,
  description  text,
  retail_price numeric,
  similarity   float
)
LANGUAGE sql STABLE
AS $$
  SELECT
    i.item_id,
    i.item_name,
    i.description,
    i.retail_price,
    1 - (e.embedding <=> query_embedding) AS similarity
  FROM item_embeddings e
  JOIN items i ON i.item_id = e.item_id
  WHERE i.is_active = true
  ORDER BY e.embedding <=> query_embedding
  LIMIT match_count;
$$;
